### ISSUE TITLE
console error: failed to check broadcast

### ISSUE THREAD

**Issue by mnods** [catalyst/moodle-tool_broadcast#16]
Hi Matt, thanks for this.

FYI
mdl 3.9.3+ (Build: 20210108)
$plugin->release = '2020061800';
so message doesn't load
tried with fordson and boost (below from boost)
seems ok in mdl 3.8

`first.js:322 Error: Failed to check broadcast messages
    at first.js:322
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as rejectWith] (jquery-3.4.1.min.js:2)
    at Object.s.<computed> [as reject] (jquery-3.4.1.min.js:2)
    at first.js:43
    at Array.forEach (<anonymous>)
    at Array.f (first.js:43)
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2)
    at l (jquery-3.4.1.min.js:2)
(anonymous) @ first.js:322
c @ jquery-3.4.1.min.js:2
fireWith @ jquery-3.4.1.min.js:2
s.<computed> @ jquery-3.4.1.min.js:2
(anonymous) @ first.js:43
f @ first.js:43
c @ jquery-3.4.1.min.js:2
fireWith @ jquery-3.4.1.min.js:2
l @ jquery-3.4.1.min.js:2
(anonymous) @ jquery-3.4.1.min.js:2
load (async)
send @ jquery-3.4.1.min.js:2
ajax @ jquery-3.4.1.min.js:2
call @ first.js:43
l @ first.js:322
(anonymous) @ first.js:322
Promise.then (async)
f.init @ first.js:322
(anonymous) @ view.php?id=17073&theme=boost:2733
execCb @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
(anonymous) @ require.min.js:5
setTimeout (async)
req.nextTick @ require.min.js:5
o @ require.min.js:5
requirejs @ require.min.js:5
(anonymous) @ view.php?id=17073&theme=boost:2733
execCb @ require.min.js:5
check @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
emit @ require.min.js:5
check @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
emit @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
h @ require.min.js:5
completeLoad @ require.min.js:5
onScriptLoad @ require.min.js:5
load (async)
req.load @ require.min.js:5
load @ require.min.js:5
load @ require.min.js:5
fetch @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
enable @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
h @ require.min.js:5
completeLoad @ require.min.js:5
onScriptLoad @ require.min.js:5
load (async)
req.load @ require.min.js:5
load @ require.min.js:5
load @ require.min.js:5
fetch @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
enable @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
(anonymous) @ require.min.js:5
setTimeout (async)
req.nextTick @ require.min.js:5
o @ require.min.js:5
requirejs @ require.min.js:5
(anonymous) @ view.php?id=17073&theme=boost:2496
first.js:322 Error: Failed to check broadcast messages
    at first.js:322
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as rejectWith] (jquery-3.4.1.min.js:2)
    at Object.s.<computed> [as reject] (jquery-3.4.1.min.js:2)
    at first.js:43
    at Array.forEach (<anonymous>)
    at Array.f (first.js:43)
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2)
    at l (jquery-3.4.1.min.js:2)
(anonymous) @ first.js:322
c @ jquery-3.4.1.min.js:2
fireWith @ jquery-3.4.1.min.js:2
s.<computed> @ jquery-3.4.1.min.js:2
(anonymous) @ first.js:43
f @ first.js:43
c @ jquery-3.4.1.min.js:2
fireWith @ jquery-3.4.1.min.js:2
l @ jquery-3.4.1.min.js:2
(anonymous) @ jquery-3.4.1.min.js:2
load (async)
send @ jquery-3.4.1.min.js:2
ajax @ jquery-3.4.1.min.js:2
call @ first.js:43
l @ first.js:322
setInterval (async)
(anonymous) @ first.js:322
Promise.then (async)
f.init @ first.js:322
(anonymous) @ view.php?id=17073&theme=boost:2733
execCb @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
(anonymous) @ require.min.js:5
setTimeout (async)
req.nextTick @ require.min.js:5
o @ require.min.js:5
requirejs @ require.min.js:5
(anonymous) @ view.php?id=17073&theme=boost:2733
execCb @ require.min.js:5
check @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
emit @ require.min.js:5
check @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
emit @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
h @ require.min.js:5
completeLoad @ require.min.js:5
onScriptLoad @ require.min.js:5
load (async)
req.load @ require.min.js:5
load @ require.min.js:5
load @ require.min.js:5
fetch @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
enable @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
h @ require.min.js:5
completeLoad @ require.min.js:5
onScriptLoad @ require.min.js:5
load (async)
req.load @ require.min.js:5
load @ require.min.js:5
load @ require.min.js:5
fetch @ require.min.js:5
check @ require.min.js:5
enable @ require.min.js:5
enable @ require.min.js:5
(anonymous) @ require.min.js:5
(anonymous) @ require.min.js:5
each @ require.min.js:5
enable @ require.min.js:5
init @ require.min.js:5
(anonymous) @ require.min.js:5
setTimeout (async)
req.nextTick @ require.min.js:5
o @ require.min.js:5
requirejs @ require.min.js:5
(anonymous) @ view.php?id=17073&theme=boost:2496
`

**Comment by mdjnelson** [comment]
Are you able to provide any replication steps? Also, what browser are you using and have you tried updating to the latest 3.9 version?

**Comment by mnods** [comment]
not really sorry, it was quite random, seemed to pop up after an amount of time, but yes i've updated since this and doesn't seem to be happening now - cheers.
