### ISSUE TITLE
Migrate to github actions

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-tool_broadcast#20]
CI should be run in github actions and in travis.

**Comment by mdjnelson** [comment]
I am working on this now. I removed usage of Travis as eventually it will stop working once you reach their limit and most other plugins removed the file.

**Comment by mdjnelson** [comment]
Already created a MR for removing Travis.

**Comment by mdjnelson** [comment]
Remove Travis - https://github.com/catalyst/moodle-tool_broadcast/pull/19
Add GHA - https://github.com/catalyst/moodle-tool_broadcast/pull/23

**Comment by mdjnelson** [comment]
Done.
