### ISSUE TITLE
Unable to click add new Broadcast

### ISSUE THREAD

**Issue by xzrians** [catalyst/moodle-tool_broadcast#38]
![image](https://user-images.githubusercontent.com/47202302/170603722-9fa7477b-19d5-42ac-95a7-5a9cb9546ccf.png)

Hi Guys. i faced this issue when i install this plugin. 
Do you have any idea?
Moodle version 3.9.13+

**Comment by dmitriim** [comment]
We are going to retire this plugin. Please consider using https://github.com/catalyst/moodle-local_sitenotice
